### PR TITLE
add missing omc_file files

### PR DESCRIPTION
**Pull request by joshbode**
~obtained from [omc_file.c](https://raw.githubusercontent.com/OpenModelica/OpenModelica/master/OMCompiler/SimulationRuntime/c/util/omc_file.c) and [omc_file.h](https://raw.githubusercontent.com/OpenModelica/OpenModelica/master/OMCompiler/SimulationRuntime/c/util/omc_file.h)~
Added imports to build

### CODE REVIEW

**Comment by joshbode** [comment]
not sure if this is the right way to do this, but this fixed the build of this package on my system (arch linux)

**Comment by adeas31** [comment]
Strange as none of our build servers are reporting any error.
Anyway I think you don't need to copy the files just add the following lines to `OMOptim/build/OMOptimLib.pro` at line `264`,

$${OPENMODELICAHOME}/include/omc/c/util/omc_file.h \
$${OPENMODELICAHOME}/include/omc/c/util/omc_file.c \

**Comment by joshbode** [comment]
oh, great - I wondered why the `read_matlab4` includes didn't fail - I'll make your suggested change :)

**Comment by joshbode** [comment]
done

**Comment by joshbode** [comment]
Awesome - thank you!

**Pull request merged**
